### ISSUE TITLE
Check if LODs can speed up performance

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#210]
Unity can help create LOD versions of meshes at runtime. We should check how much performance we can get with it.

* Blog post about possibilities: https://thegamedev.guru/unity-gpu-performance/lod-level-of-detail/
* a Unity package for it (MIT): https://github.com/Whinarn/UnityMeshSimplifier

**Comment by ThomasMountainborn** [comment]
Knowing what we know now from building the bsp tree meshes, I think merging meshes would yield more performance rather than generating lods. The meshes are all very low poly already. If meshes are < 100 vertices, the GPU can't handle them efficiently. Combining many meshes into one larger meshes yields better performance.
