### ISSUE TITLE
Head sizes change when the eating animation is played

### ISSUE THREAD

**Issue by Romeeey** [GothicVRProject/GothicVR#346]
1.) Observe NPC 322 (Schatten) in his routine
2.) He will put out an item (bread) and eat it
3.) While eating his head gets smaller and thinner
4.) When the eating animation is over, the head pops back to normal size

Expected behaviour: 
The head should have the same size throughout all animations.
This problem doesn't happen always. NPC 554 (Buddler) works fine. 

![image](https://github.com/GothicVRProject/GothicVR/assets/121696184/72eb589d-de8f-4acd-8f3a-dba2b812e7d3)

**Comment by JaXt0r** [comment]
It's not a bug, it's a feature. I checked with original Gothic 1 and it is normal behaviour. I think the issue is, that at PB no one took care of improving the head's morph meash for this specific head.
![Head-shrink-eat](https://github.com/GothicVRProject/GothicVR/assets/120568393/ab2fd662-def2-4a4d-8a75-d72798a45934)
