### ISSUE TITLE
Set normals to meshes

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#79]
Currently there are no normals set on npcs, items, and world.

We need to add it (is already deliverd by phoenix, btw.) to have proper light reflections.

**Comment by JaXt0r** [comment]
I checked, but don't see a difference with/without normals.

Maybe it's due to the changed Shader?

Hint: ZenGine doesn't support normal maps. It was introduced with DX11 renderer first: https://www.worldofgothic.de/dl/download_590.htm

**Comment by JaXt0r** [comment]
Update: Set shader to "Standard", then lightning and shadows are back. Interestingly with the normals it looks worse. Maybe there'S something wrong with the Vector3 (e.g. need to be divided by 100)?

without normals:
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/db5f4675-cf51-491f-adec-7ac224001c9e)

with normals:
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/aa66aa24-4151-4f92-8c57-5a965c295921)

**Comment by vincolus** [comment]
@JaXt0r dunno if it still exists, but i suggest trying to make use of the LIT_* or UNLIT_* shaders I built a while ago, try if they make sense and then write them down in HLSL or similar

**Comment by JaXt0r** [comment]
@vincolus - What do you mean? As improvement for the shader performance or quality? We move to URP next week and can reuse your (UN)LIT ones again.

**Comment by vincolus** [comment]
i justhad a quick look and it seemed like shading is a bit messed up and i
remember it looked better with the shadee i did a while back, which can
also handle recursive tranparent objects due to use of dithering.
not 💯 percent sure though, since i only had a brief impression and wanted
to toss in my two cents in hope of being at least a small aid

JaXt0r ***@***.***> schrieb am Sa., 10. Juni 2023, 19:35:
